# ==============================
# 常用配置
# ==============================
# 输入文件表格, 支持xlsx,txt和csv格式(txt也是csv格式)
# in: 昵称抢注情况.xlsx
# in: nickname_list.txt
in: nickname_list.csv

# 默认的cdkey过期时间
expire_date: "2024-12-31 23:59:59"

# 行列数从1开始
# 表格中数据所在行
row:
  begin: 1

# 表格中数据所在列, 其中`expire`可选
col:
  server: 3
  name: 1
  cdkey: 2
  expire: 4

# ==============================
# 非常用配置
# ==============================
# 导出sql配置
sql:
  # 表名
  table: dc_name_cdkey
  # 单条sql的值的数量长度(生成临时文件用, 不是最终sql文件)
  len: 1000

# 资源路径
assets: assets
